<?xml version="1.0" encoding="utf-8"?><Database Name="REDDatabase" Class="DataClassesLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database\REDDatabase.mdf;Integrated Security=True" SettingsObjectName="RED.Properties.Settings" SettingsPropertyName="REDDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Default]" Member="Defaults">
    <Type Name="Default">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DataId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeStamp" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.GPSData" Member="GPSDatas">
    <Type Name="GPSData">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TimeStamp" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="FixObtained" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="FixQuality" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfSatellites" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CurrentAltitude" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Speed" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="SpeedAngle" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>